# Generated by Django 4.1.4 on 2022-12-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_collection_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['discount']},
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
